In [30]:
import pandas as pd

df=pd.read_csv("/home/shyam/Desktop/code/python/py_internshala_condingninjas/Machine_Learning/Python_Life/Placement_Data_Full_Class.csv")

df

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1      M  67.00   Others  91.00   Others  Commerce     58.00   
1        2      M  79.33  Central  78.33   Others   Science     77.48   
2        3      M  65.00  Central  68.00  Central      Arts     64.00   
3        4      M  56.00  Central  52.00  Central   Science     52.00   
4        5      M  85.80  Central  73.60  Central  Commerce     73.30   
..     ...    ...    ...      ...    ...      ...       ...       ...   
210    211      M  80.60   Others  82.00   Others  Commerce     77.60   
211    212      M  58.00   Others  60.00   Others   Science     72.00   
212    213      M  67.00   Others  67.00   Others  Commerce     73.00   
213    214      F  74.00   Others  66.00   Others  Commerce     58.00   
214    215      M  62.00  Central  58.00   Others   Science     53.00   

      degree_t workex  etest_p specialisation  mba_p      status    salary  
0     Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1     Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2    Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3     Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4    Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0  
..         ...    ...      ...            ...    ...         ...       ...  
210  Comm&Mgmt     No     91.0        Mkt&Fin  74.49      Placed  400000.0  
211   Sci&Tech     No     74.0        Mkt&Fin  53.62      Placed  275000.0  
212  Comm&Mgmt    Yes     59.0        Mkt&Fin  69.72      Placed  295000.0  
213  Comm&Mgmt     No     70.0         Mkt&HR  60.23      Placed  204000.0  
214  Comm&Mgmt     No     89.0         Mkt&HR  60.22  Not Placed       NaN  

[215 rows x 15 columns]

In [31]:
df.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [32]:
df.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [33]:
df["salary"]=df["salary"].fillna(df['salary'].mode()[0])
df.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed  300000.0  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [34]:
#2 method Simple imputer

In [56]:
import numpy as np


In [57]:
import numpy as np

from sklearn.impute import SimpleImputer

In [67]:

import pandas as pd


imputer =SimpleImputer(missing_values=np.nan,strategy='mean')

data=[[12,13,np.nan],[13,14,np.nan],[36,np.nan,44]]

data

[[12, 13, nan], [13, 14, nan], [36, nan, 44]]

In [86]:

imputer = imputer.fit(data)

# Imputing the data	
data = imputer.transform(data)

print("Imputed Data : \n", data)


Imputed Data : 
 [[12. 23. 23. 34.]
 [ 2.  3. 23. 34.]
 [ 7. 13. 23. 34.]]


In [92]:
from sklearn.impute import SimpleImputer

data=[[12,23,23,np.nan],[2,3,np.nan,34],[np.nan,np.nan,23,34]]

replace=SimpleImputer(missing_values=np.nan,strategy="mean")


# hii=replace.fit(data)
# bye=hii.transform(data)
# bye
see=replace.fit_transform(data)
see

array([[12., 23., 23., 34.],
       [ 2.,  3., 23., 34.],
       [ 7., 13., 23., 34.]])

In [99]:
from sklearn.impute import SimpleImputer

data=[[12,23,23,np.nan],[2,3,np.nan,34],[np.nan,np.nan,23,34]]

replace=SimpleImputer(missing_values=np.nan,strategy="mean")


# hii=replace.fit(data)
# bye=hii.transform(data)
# bye
see=replace.fit_transform(data)
see


array([[12., 23., 23., 34.],
       [ 2.,  3., 23., 34.],
       [ 7., 13., 23., 34.]])

In [102]:
from sklearn.impute import SimpleImputer


data=[[1,2,3,np.nan,4],[3,np.nan,4,9,8]]

data

[[1, 2, 3, nan, 4], [3, nan, 4, 9, 8]]

In [104]:
hi=SimpleImputer(missing_values=np.nan,strategy="mean")
see=hi.fit_transform(data)
see

array([[1., 2., 3., 9., 4.],
       [3., 2., 4., 9., 8.]])

In [ ]:
#feature encoding

In [1]:
import pandas as pd

df=pd.read_csv("/home/shyam/Desktop/code/python/py_internshala_condingninjas/Machine_Learning/Python_Life/airport.csv")
df

id    ident           type  \
0     26555     VIDP  large_airport   
1     26434     VABB  large_airport   
2     26618     VOMM  large_airport   
3     35145     VOBL  large_airport   
4     26444     VAGO  large_airport   
..      ...      ...            ...   
332   46625  IN-0062  small_airport   
333   46640  IN-0064  small_airport   
334   46561  IN-0038       heliport   
335  319166  IN-0101  small_airport   
336   46557  IN-0034  small_airport   

                                          name  latitude_deg  longitude_deg  \
0          Indira Gandhi International Airport     28.566500      77.103104   
1    Chhatrapati Shivaji International Airport     19.088699      72.867897   
2                Chennai International Airport     12.990005      80.169296   
3             Kempegowda International Airport     13.197900      77.706299   
4                    Goa International Airport     15.380800      73.831398   
..                                         ...           ...            ...   
332                            Shirpur Airport     21.323999      74.956734   
333                           Umaria Air Field     23.532514      80.808220   
334           Upper Tadong Indian Army Helipad     27.306717      88.599650   
335                         Vanasthali Airport     26.407627      75.870128   
336                        Vijay Nagar Airport     19.884100      73.840567   

     elevation_ft iso_region   municipality  scheduled_service gps_code  \
0           777.0      IN-DL      New Delhi                  1     VIDP   
1            39.0      IN-MM         Mumbai                  1     VABB   
2            52.0      IN-TN        Chennai                  1     VOMM   
3          3000.0      IN-KA      Bangalore                  1     VOBL   
4           150.0      IN-GA  Vasco da Gama                  1     VOGO   
..            ...        ...            ...                ...      ...   
332           NaN      IN-MM        Shirpur                  0      NaN   
333        1510.0      IN-MP         Umaria                  0      NaN   
334           NaN      IN-SK   Upper Tadong                  0      NaN   
335           NaN      IN-RJ     Vanasthali                  0      NaN   
336           NaN      IN-MM    Vijay Nagar                  0      NaN   

    iata_code local_code  year_built  year_tier Closed  \
0         DEL        NaN      1930.0     1950.0      n   
1         BOM        NaN      1942.0     1950.0      n   
2         MAA        NaN      1910.0     1950.0      n   
3         BLR        NaN      2008.0     2010.0      n   
4         GOI        NaN      1955.0     1955.0      n   
..        ...        ...         ...        ...    ...   
332       NaN        NaN         NaN        NaN      n   
333       NaN        NaN         NaN        NaN      n   
334       NaN        NaN         NaN        NaN      n   
335       NaN        NaN         NaN        NaN      n   
336       NaN        NaN         NaN        NaN      n   

                                          home_link  \
0                    http://www.newdelhiairport.in/   
1                               http://www.csia.in/   
2                                               NaN   
3    http://www.bengaluruairport.com/home/home.jspx   
4                                               NaN   
..                                              ...   
332                                             NaN   
333                                             NaN   
334                                             NaN   
335                                             NaN   
336                                             NaN   

                                        wikipedia_link  \
0    http://en.wikipedia.org/wiki/Indira_Gandhi_Int...   
1    http://en.wikipedia.org/wiki/Chhatrapati_Shiva...   
2    http://en.wikipedia.org/wiki/Chennai_Internati...   
3    https://en.wikipedia.org/wiki/Kempegowda_Inter...   
4         http://en.wikipedia.org/wiki/Dab

In [2]:
df["type"].value_counts()

type
small_airport     157
medium_airport    101
heliport           41
closed             27
large_airport      11
Name: count, dtype: int64

In [5]:
#five different categories
pd.get_dummies(df,columns=["type"])


id    ident                                       name  latitude_deg  \
0     26555     VIDP        Indira Gandhi International Airport     28.566500   
1     26434     VABB  Chhatrapati Shivaji International Airport     19.088699   
2     26618     VOMM              Chennai International Airport     12.990005   
3     35145     VOBL           Kempegowda International Airport     13.197900   
4     26444     VAGO                  Goa International Airport     15.380800   
..      ...      ...                                        ...           ...   
332   46625  IN-0062                            Shirpur Airport     21.323999   
333   46640  IN-0064                           Umaria Air Field     23.532514   
334   46561  IN-0038           Upper Tadong Indian Army Helipad     27.306717   
335  319166  IN-0101                         Vanasthali Airport     26.407627   
336   46557  IN-0034                        Vijay Nagar Airport     19.884100   

     longitude_deg  elevation_ft iso_region   municipality  scheduled_service  \
0        77.103104         777.0      IN-DL      New Delhi                  1   
1        72.867897          39.0      IN-MM         Mumbai                  1   
2        80.169296          52.0      IN-TN        Chennai                  1   
3        77.706299        3000.0      IN-KA      Bangalore                  1   
4        73.831398         150.0      IN-GA  Vasco da Gama                  1   
..             ...           ...        ...            ...                ...   
332      74.956734           NaN      IN-MM        Shirpur                  0   
333      80.808220        1510.0      IN-MP         Umaria                  0   
334      88.599650           NaN      IN-SK   Upper Tadong                  0   
335      75.870128           NaN      IN-RJ     Vanasthali                  0   
336      73.840567           NaN      IN-MM    Vijay Nagar                  0   

    gps_code  ... Closed                                       home_link  \
0       VIDP  ...      n                  http://www.newdelhiairport.in/   
1       VABB  ...      n                             http://www.csia.in/   
2       VOMM  ...      n                                             NaN   
3       VOBL  ...      n  http://www.bengaluruairport.com/home/home.jspx   
4       VOGO  ...      n                                             NaN   
..       ...  ...    ...                                             ...   
332      NaN  ...      n                                             NaN   
333      NaN  ...      n                                             NaN   
334      NaN  ...      n                                             NaN   
335      NaN  ...      n                                             NaN   
336      NaN  ...      n                                             NaN   

                                        wikipedia_link  \
0    http://en.wikipedia.org/wiki/Indira_Gandhi_Int...   
1    http://en.wikipedia.org/wiki/Chhatrapati_Shiva...   
2    http://en.wikipedia.org/wiki/Chennai_Internati...   
3    https://en.wikipedia.org/wiki/Kempegowda_Inter...   
4         http://en.wikipedia.org/wiki/Dabolim_Airport   
..                                                 ...   
332                                                NaN   
333                                                NaN   
334                                                NaN   
335                                                NaN   
336                                                NaN   

                                              keywords    score type_closed  \
0                              Palam Air Force Station    51475       False   
1                  Bombay, Sahar International Airport  1014475       False   
2                                                  NaN    51150       False   
3                                                  NaN    51200       False   
4    Goa Airport, Dabolim Navy Airbase, ________隷怄_...    

In [ ]:
#label encoding
# textual to numeric or target because it may cause errors

In [6]:
df1=pd.read_csv("/home/shyam/Desktop/code/python/py_internshala_condingninjas/Machine_Learning/Python_Life/Iris.csv")
df1

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [8]:
df1.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
#iris-setosa to 0 and other are like 1,2,3, etc

In [9]:
from sklearn.preprocessing import LabelEncoder

l=LabelEncoder()

df1["Species"]=l.fit_transform(df1['Species'])

In [10]:
df1

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [ ]:
#see on species is changing 0,1, and 2 with clear target output

In [ ]:
#features scaling

In [3]:
# Python Program to implement reverse and add function

# Iterative function to reverse digits of num
def reverseDigits(num):
	rev_num = 0
	while (num > 0):
		rev_num = rev_num * 10 + num % 10
		num = num//10
	return rev_num

# Function to check whether
# the number is palindrome or not
def isPalindrome(num):
	return (reverseDigits(num) == num)

# Reverse and Add Function
def ReverseandAdd(num):
	rev_num = 0
	while (num <= 4294967295):
		# Reversing the digits of the number
		rev_num = reverseDigits(num)

		# Adding the reversed number
		# with the original
		num = num + rev_num
		print(num)

		# Checking whether the number
		# is palindrome or not
		if(isPalindrome(num)):
			print (num)
			break
		else:
			if (num > 4294967295):
				print ("No palindrome exist")

# Driver Code
ReverseandAdd(195)
ReverseandAdd(265)


786
1473
5214
9339
9339
827
1555
7106
13123
45254
45254
