In [16]:
import numpy as np
d=np.array([3,4,5])
# d.nbytes
d.dtype

dtype('int64')

In [92]:
import numpy as np

a=np.array([[1,23,4],[4,56,7]])
a

array([[ 1, 23,  4],
       [ 4, 56,  7]])

In [94]:
a.ndim

2

In [28]:
# a[0,:]
a[1,:]

array([ 4, 56,  7])

In [38]:
a[:,2]
# b[:,2]

array([4, 6, 7])

In [37]:
import numpy as np

a=np.array([[1,23,4],[4,5,6],[4,5,7]])
a

array([[ 1, 23,  4],
       [ 4,  5,  6],
       [ 4,  5,  7]])

In [11]:
a.nbytes

72

In [48]:
# b=np.array([[1,23,4],[4,5,6],[4,5,6]])
b=np.array([[[1,23,4],[4,5,6],[4,5,6]]])
# b
b[0,:]
# b[0,0:2]
# # b[:,0]

array([[ 1, 23,  4],
       [ 4,  5,  6],
       [ 4,  5,  6]])

In [8]:
c=np.array([[[12,34,45],[4,5,6]],[[12,34,45],[4,5,6]]])
c

array([[[12, 34, 45],
        [ 4,  5,  6]],

       [[12, 34, 45],
        [ 4,  5,  6]]])

In [10]:
c.nbytes

96

In [9]:
c.ndim


3

In [6]:
b.ndim

3

In [4]:
a.ndim

2

In [19]:
s=np.zeros((2,3))
s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [95]:

s=np.ones((2,3,4),int)
s


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [96]:
s+2

array([[[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]])

In [62]:
# # s=np.zeros((1,9))
# s=np.zeros((2,3))
s=np.full((3,3),45)
s
s

array([[45, 45, 45],
       [45, 45, 45],
       [45, 45, 45]])

In [67]:
s=np.full((3,3),3,float)
s

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [71]:
f=np.random.rand(4,4)
f

array([[0.88487023, 0.54595459, 0.21382225, 0.22872658],
       [0.86115569, 0.20830873, 0.90109964, 0.19123903],
       [0.99554402, 0.53154643, 0.07604638, 0.85002068],
       [0.81885005, 0.60798927, 0.11687004, 0.12989784]])

In [82]:
e=np.identity(2)
e=np.identity(3)
e


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
g=np.array([1,2,3,4])
h=g.copy()
h[0]=32
print(g)
print(h)

[1 2 3 4]
[32  2  3  4]


In [93]:
a+2

array([[ 3, 25,  6],
       [ 6, 58,  9]])

In [118]:
dice=np.random.randint(1,7)
dice

1

In [154]:
np.random.seed(3)

dice=np.random.randint(7)
dice


2

In [153]:
np.random.seed(4)

dice=np.random.randint(7)
dice


2

In [159]:
h=np.random.rand(3,2)
h

array([[0.14537014, 0.4531723 ],
       [0.21557701, 0.35390507],
       [0.49263593, 0.91330145]])

In [164]:
j=np.array([12,3,4,5,6,7,8,9])

j

array([12,  3,  4,  5,  6,  7,  8,  9])

In [165]:
j.reshape(4,2)

array([[12,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

# searching and sorting

In [169]:
a=np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [171]:
np.where(a==4)

(array([3]),)

In [175]:
np.where(a%2==0)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# sorting

In [177]:
b=np.array([13244,3444,1])
c=np.array(["sai","goli","spydy","anna"])
np.sort(b)

array([    1,  3444, 13244])

In [183]:
# c.sort()
np.sort(c)
c

array(['anna', 'goli', 'sai', 'spydy'], dtype='<U5')