# 1D Array

In [2]:
import numpy as np

a=np.array([1])
a
print(a)






array([1])

In [3]:
a.ndim

1

In [4]:
type(a)

numpy.ndarray

# 2D Array

In [6]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b.ndim

2

In [8]:
type(b)

numpy.ndarray

# 3D Array 

In [10]:
c=np.array([[1,2,3,4],[5,6,7,8],[7,8,9,9]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [7, 8, 9, 9]])

In [12]:
c.ndim

2

In [13]:
d=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[2,3,4,5]]])
d

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [2, 3, 4, 5]]])

In [14]:
d.ndim

3