In [5]:
import numpy as np

a=np.array([1,2,3,4])

a

array([1, 2, 3, 4])

In [ ]:
b=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[2,3,4,5]]])
b

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [2, 3, 4, 5]]])

In [ ]:
print(a[0])

In [12]:
b=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[2,3,4,5]]])
b

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [2, 3, 4, 5]]])

In [13]:
c=np.array([[1,2,3,4],[5,6,7,8]])

c


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
c[0,2]

3

In [15]:
c[0,1]+c[1,1]

8

In [16]:
b.shape

(2, 2, 4)

In [17]:
import numpy as np

arr=np.array([1,2,3,4])

arr

array([1, 2, 3, 4])

In [18]:
for i in arr:
    print(i)

1
2
3
4


In [25]:
import numpy as np

arr2=np.array([[1,2,3,4],[4,5,6,7]])

arr2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [24]:
for i in arr2:
    print(i)
    break

for j in i:
    print(j)

[1 2 3 4]
1
2
3
4


In [26]:
for i in arr2:
    for j in i:
        print(j)

1
2
3
4
4
5
6
7
