In [27]:
import numpy as np

a=np.array([1,2,3,4,5,6,6,5])

# c=np.where(a==4)


In [15]:
c=np.where(a==5)
c

(array([4, 7]),)

In [35]:
b=np.where(a%2==0)
b

(array([1, 3, 5, 6]),)

In [24]:
# b=np.where(a%2==0)
b=np.where(a/2==0)
b

(array([], dtype=int64),)

In [31]:
# type(a)
# a.shape
a.ndim

1

sorting

In [36]:
import numpy as np

a=np.array([5,6,6,51,2,3,4,])

b=np.sort(a)
b


array([ 2,  3,  4,  5,  6,  6, 51])

In [37]:
import numpy as np

a=np.array(["saikrushna","goli","kavita","shyam","purushottam"])

b=np.sort(a)
b

array(['goli', 'kavita', 'purushottam', 'saikrushna', 'shyam'],
      dtype='<U11')

In [40]:
import numpy as np

a=np.array(['kavita', 'purushottam', 'saikrushna', 'shyam'])
print(a)
c=np.where(a=="saikrushna")
print(c)
b=np.sort(a)
print(b)

['kavita' 'purushottam' 'saikrushna' 'shyam']
(array([2]),)
['kavita' 'purushottam' 'saikrushna' 'shyam']


In [6]:
import numpy as np

hii=np.array([23,45,555,4])
bye=np.sort(hii)



bye

array([  4,  23,  45, 555])