In [27]:
import numpy as np

a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
a.shape

(12,)

(4 rows ,each row 3 elements)

In [4]:
b=a.reshape(4,3)

b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
b.ndim

2

In [6]:
b.shape

(4, 3)

In [12]:
c=np.array([[[ 1,  2,  3],[10, 11, 12]],
            [[ 1,  2,  3],[10, 11, 12]]])
c.ndim

3

In [13]:
c.shape

(2, 2, 3)

In [14]:
b.shape

(4, 3)

In [28]:
new_a=a.reshape(2,3,2)


In [20]:
a.shape

(12,)

In [21]:
a.ndim

1

In [24]:
new=a.reshape(2,6)

In [23]:
a.ndim

1

In [25]:
new.ndim

2

In [29]:
new_a.ndim

3

2d to 1d

In [30]:
flattening_array=np.array([[1,2,3],[4,5,6]])
flattening_array

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
flattening_array.shape

(2, 3)

In [32]:
flattening_array.ndim

2

In [ ]:
# convert to 1d

In [33]:
see=flattening_array.reshape(-1)



In [34]:
see

array([1, 2, 3, 4, 5, 6])

In [36]:
see.shape

(6,)