In [18]:
import numpy as np

a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
a[1:4]

array([2, 3, 4])

In [15]:
c=np.array([[1,2,3,4],[5,6,7,8],[7,8,9,9]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [7, 8, 9, 9]])

In [24]:
e=np.array([[1,2,3],[4,5,6]])
e

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
e[0,0:2]
print(e[1,:])

[4 5 6]
